export let hangyeOption = [
    {text: '全部行业', value: -1},
    {text: '药品', value: 0},
    {text: '保健品', value: 1},
    {text: '乳品', value: 2},
    {text: '其他', value: 2},
];
export let xianbieOption = [
    {text: '全部线别', value: -1},
    {text: '固体stick线', value: 0},
    {text: '液体stick线', value: 1},
    {text: '听装线', value: 2},
    {text: '泡罩线', value: 3},
    {text: '软双铝线', value: 4},
    {text: '制粒线', value: 5},
    {text: '其他', value: 6},
];
export let jixingOption = [
    {text: '全部剂型', value: -1},
    {text: '颗粒', value: 0},
    {text: '丸剂', value: 1},
    {text: '粉剂', value: 2},
    {text: '干混悬剂', value: 3},
    {text: '液体', value: 4},
    {text: '片剂', value: 5},
    {text: '胶囊', value: 6},
    {text: '其他', value: 7},
];
export let guigeOption = [
    {text: '全部装量规格', value: -1},
    {text: '颗粒', value: 0},
    {text: '丸剂', value: 1},
    {text: '粉剂', value: 2},
    {text: '干混悬剂', value: 3},
    {text: '液体', value: 4},
    {text: '片剂', value: 5},
    {text: '胶囊', value: 6},
    {text: '其他', value: 7},
];
export let daikuanOption = [
    {text: '全部袋宽', value: -1},
    {text: '14.9', value: 0},
    {text: '16.5', value: 1},
    {text: '18.1', value: 2},
    {text: '19.6', value: 3},
    {text: '21.2', value: 4},
    {text: '22.8', value: 5},
    {text: '24.3', value: 6},
    {text: '25.9', value: 7},
    {text: '27.5', value: 8},
    {text: '29.0', value: 9},
    {text: '30.6', value: 10},
    {text: '32.2', value: 11},
    {text: '33.8', value: 12},
    {text: '35.3', value: 13},
    {text: '36.9', value: 14},
    {text: '38.5', value: 15},
    {text: '40.0', value: 16},
    {text: '42.0', value: 17},
    {text: '43.6', value: 18},
    {text: '45.1', value: 19},
    {text: '46.7', value: 20},
    {text: '48.3', value: 21},
    {text: '49.8', value: 22},
    {text: '54.6', value: 23},
    {text: '79.7', value: 24},
    {text: '其他', value: 25},
];
export let baozhuangOption = [
    {text: '全部包装', value: -1},
    {text: '装盒', value: 0},
    {text: '装罐', value: 1},
    {text: '装袋', value: 2},
    {text: '其他', value: 3},
];
export let zhuangheOpion = [
    {text: '全部装盒形式', value: -1},
    {text: '单层有序', value: 0},
    {text: '双层有序', value: 1},
    {text: '三层有序', value: 2},
    {text: '斜装装盒', value: 3},
    {text: '装托装盒', value: 4},
    {text: '枕式袋装盒', value: 5},
    {text: '侧装说明书', value: 6},
    {text: '其他', value: 7},
];
export let jieduanOption = [
    {text: '全部项目阶段', value: -1},
    {text: '商机挖掘阶段', value: 0},
    {text: '需求引导阶段', value: 1},
    {text: '立项阶段', value: 2},
    {text: 'URS及方案确认阶段', value: 3},
    {text: '报价阶段', value: 4},
    {text: '投标阶段', value: 5},
    {text: '合同谈判阶段', value: 6},
];
export let shichangOption = [
    {text: '全部细分市场', value: -1},
    {text: '大规格中药颗粒', value: 0},
    {text: '头孢类颗粒', value: 1},
    {text: '干混悬剂', value: 2},
    {text: '蒙脱石散', value: 3},
    {text: '滴丸', value: 4},
    {text: '水丸', value: 5},
    {text: '中药饮片超微粉', value: 6},
    {text: '中药膏方', value: 7},
    {text: '中药口服液', value: 8},
    {text: '西药口服', value: 9},
    {text: '软双铝', value: 10},
    {text: '益生菌', value: 11},
    {text: '蛋白粉', value: 12},
    {text: '代餐粉', value: 13},
    {text: '液体保健品', value: 14},
    {text: '奶粉听装线', value: 15},
    {text: '奶粉stick线', value: 16},
    {text: '其他', value: 17},
];